# _config.yml
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark" # good for crypto projects

title: "COINBEV"
subtitle: "We take \"Liquid Staking\" literally... PROST! 🍺"
repository: "CoinBevAI/coinbevai.github.io"
baseurl: ""
url: "https://coinbevai.github.io"
logo: "/assets/images/logo.jpg"

# Add this plugins section
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache  # This is required for Minimal Mistakes theme

# Defaults for all pages
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      share: true
      related: false
      toc: true
      toc_sticky: true

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Additional settings for crypto project
atom_feed:
  hide: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/coinbev"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/coinbevai"

# Remove "Powered by" text completely and customize copyright
copyright: "© 2025 CoinBev - All rights reserved"